{% set name = "types-nmap" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-nmap-{{ version }}.tar.gz
  sha256: fc4446bc3bcbf19839fbb5bc0ddd6248f02b46863818e701216a84ee5ab14320

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/nmap-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for nmap
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
